### PR TITLE
fix: Improve responsiveness

### PR DESCRIPTION
**Pull request by Agnik7**
Solves Issue #1 
Performed the following changes: 

- Improved responsiveness to cater to the mobile audience.

- Optimized the CSS a bit. 

Here's how the site looks in mobile now:

Responsiveness fix

@21R01A7263 please have a look.

### CODE REVIEW

**Comment by gaurav-saiteja** [comment]
Site has flex-direction:column even in the desktop viewport. Here's the preview.

image

Optimally, it should revert back to flex-direction:column for large screen sizes

**Comment by Agnik7** [comment]
@21R01A7263 I had edited the CSS for a better user experience. 

Here is the default state in desktop mode:
Default


Here is the state after QR is generated:
QR_GENERATED


Is this alright? @21R01A7263

**Comment by gaurav-saiteja** [comment]
> @21R01A7263 I had edited the CSS for a better user experience.
> 
> Here is the default state in desktop mode: Default
> 
> Here is the state after QR is generated: QR_GENERATED
> 
> Is this alright? @21R01A7263

Hey @Agnik7. I still prefer this style for the desktop viewports.

image

**Comment by Agnik7** [comment]
@21R01A7263 I am working on it and committing by 4:00pm today.

**Pull request closed without merging**
